apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-deployment
  template:
    metadata:
      labels:
        app: lights-deployment
    spec:
      containers:
      - name: lights-deployment
        image: saeedabdulle/lights:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
