apiVersion: v1
kind: Service
metadata:
  name: heating
  namespace: argocd
spec:
  selector:
    app: heating-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
